import { MatchersV3 } from '@pact-foundation/pact';
import { firstValueFrom } from 'rxjs';
import { adapterAgainst, frontEndContract } from '../../../testing/front-end-contract';
import { Session } from '../ports/opening-hours';
import { HttpOpeningHours } from './http-opening-hours';

const CLUB_ID = '0b6e3d52-7a4f-4c1e-8f2a-9d3c5e7b1a24';

const SESSIONS: Session[] = [
  { day: 'FRIDAY', from: '20:00', to: '22:00', activity: 'Jeu libre', venue: null },
  { day: 'SATURDAY', from: '15:00', to: '17:00', activity: null, venue: { street: '1 place du Marché', postcode: '45200', town: 'Montargis' } },
];

describe('HttpOpeningHours', () => {
  it('defines the opening hours of a club', () =>
    frontEndContract
      .addInteraction()
      .given('the club G45300 is managed by the application')
      .uponReceiving('the definition of the opening hours of a club')
      .withRequest(
        'PUT',
        // The identifier of the club is generated by the back-end, which injects it from the provider state.
        MatchersV3.fromProviderState('/api/clubs/${clubId}/opening-hours', `/api/clubs/${CLUB_ID}/opening-hours`),
        (request) => request.jsonBody(SESSIONS),
      )
      .willRespondWith(204)
      .executeTest(async (mockServer) => {
        await expect(firstValueFrom(adapterAgainst(HttpOpeningHours, mockServer.url).define(CLUB_ID, SESSIONS)))
          .resolves.toBeNull();
      }));
});
